# Generated by Django 2.1 on 2018-08-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.FilePathField(default=''),
        ),
    ]
