# Generated by Django 2.1 on 2018-08-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
        migrations.RemoveField(
            model_name='post',
            name='path',
        ),
    ]
